apiVersion: v1
kind: BuildConfig
metadata:
  name: spark-base-build
spec:
  source:
    git:
        uri: "https://github.com/bodz1lla/openshift-spark.git"
        ref: "develop"
    type: Git
  strategy:
    dockerStrategy:
      noCache: true
  output:
    to:
      kind: ImageStreamTag
      name: sparkbaseimage:latest
