apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  generation: 0
  image:
    dockerImageLayers: null
    dockerImageMetadata:
      ContainerConfig: {}
      Created: null
      Id: ""
      apiVersion: "1.0"
      kind: DockerImage
    dockerImageMetadataVersion: "1.0"
    metadata:
      creationTimestamp: null
  kind: ImageStreamTag
  lookupPolicy:
    local: false
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
      openshift.io/imported-from: docker-registry.default.svc:5000/spark-openshift/spark:2.4.2
    creationTimestamp: null
    labels:
      app: spark-master
    name: spark-master:latest
  tag:
    annotations: null
    from:
      kind: DockerImage
      name: docker-registry.default.svc:5000/spark-openshift/spark:2.4.2
    generation: null
    importPolicy: {}
    name: latest
    referencePolicy:
      type: ""
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: spark-master
    name: spark-master
  spec:
    replicas: 1
    selector:
      app: spark-master
      deploymentconfig: spark-master
    strategy:
      resources: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          app: spark-master
          deploymentconfig: spark-master
      spec:
        containers:
        - image: docker-registry.default.svc:5000/spark-openshift/spark:2.4.2
          name: spark-master
          args:
            - 'master'
          resources: {}
    test: false
    triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
        - spark-master
        from:
          kind: ImageStreamTag
          name: spark:2.4.2
          namespace: spark-openshift
      type: ImageChange
  status:
    availableReplicas: 0
    latestVersion: 0
    observedGeneration: 0
    replicas: 0
    unavailableReplicas: 0
    updatedReplicas: 0
kind: List
metadata: {}
