apiVersion: v1
kind: Service
metadata:
  name: spark-master
  labels:
    name: spark-master
spec:
  ports:
  - name: master-ui
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: spark-master
    port: 7077
    protocol: TCP
    targetPort: 7077
  selector:
    name: spark-master
